// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rarflydzbssegqvphaoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcmZseWR6YnNzZWdxdnBoYW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDA5NzIsImV4cCI6MjA2MDU3Njk3Mn0.CDVkfNgc0DHNp47fY9ibbK7SIEjf9gg4GDTKCVhdTz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);